### ISSUE TITLE
Plan integration tests

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#36]
Let's have a discussion regarding integration tests and how to approach them. Most resources are related to ASP.NET Core, which is clearly not the case, so let's see what we can do.

**Why they are important**
The docs on thenewboston website are a bit outdated, so we need to ensure that our wrappers are working with the current implementations.

**Things to take into consideration**
- when/where to run them 
- general structure (I suggest creating a separate project, but feel free to state your opinions)
- what frameworks to use (we will most likely keep xUnit and Moq, but what else?)

**Comment by joshman1019** [comment]
I appreciate you opening this issue.

Do we have any source of updated documentation available? I definitely feel like there is some struggle (at least on my end) without proper docs to develop plans from. I'm almost afraid to touch anything without having been involved in the original development process. As you probably well know, it is difficult to completely shift gears within the volunteer time constraints without any prior knowledge to work from.  This is by no means a hit towards anyone on this team, you have all been great to work with. I know you are all working diligently towards the same goal. I definitely want to provide the best code possible, and also provide the best advice possible when required, but without any form of guidance available I am finding it very easy to find solutions to problems that don't even exist. If any of that makes sense. Spinning wheels as it were. 

I am very willing to dig the info out of the live server if needed, but I would honestly never do that when developing financial software of any type. This is especially true of one that is in active development and taped together with chewing gum, as Bucky has said. I might be more willing to do that if I was working with a weather tracking API, but this is very different. We almost need a coordinator for the entire project.. .someone that could be a go-between to answer questions about any new changes or documentation discrepancies. Without guidance I'm afraid we will constantly be making adjustments that will cause a cascade of changes that we have to keep going back to. 

We may also want to develop a "project triage", where we identify items that need to be completed first so that we aren't getting ahead of ourselves.  

Documentation might also be a good for our own work, that way we can provide a good experience for future developers both within out outside of this project. 

These are all just sort of "thoughts out in the open" and not directed towards anyone in particular. 

On topic though...

I believe the integration tests are a great idea, and if it were totally up to me, I'd place them in a separate project just for cleanliness. I tend to like XUnit, but I'm open to anything really.

**Comment by Mirch** [comment]
Good point regarding the documentation. I haven't worked on the main product, so I'm not really onboard with why the docs aren't updated, but I'll ask around and see what the other teams are doing and how they are handling this. 

We could dig it from live servers ourselves, buuut then there's no guarantee that the APIs won't change without us getting notified. So I'll try to set up a process for this :)

**Comment by joshman1019** [comment]
@Mirch @xmac11 @DylanGTech this is why I love working with you guys. Definitely doing the best we can! We can use our own documentation to establish some standards as well. Especially when it comes to exceptions, naming conventions, etc. Those are always a nice reference point for someone new. My profession is in government, and we like to use the "Reserved for Future Codification" lines. And so we could even go ahead and provide naming and, if needed, numbering, for things and they would be right in the docs for people to use. I hate naming... it's.... less than fun. haha

**Comment by Mirch** [comment]
Update: an issue was just opened to update the docs (https://github.com/thenewboston-developers/Management/issues/17), but I assume it might take a bit before it's done. So we might use the next few days/week to do the "less fun stuff" that you mentioned above and then get back to the real work. 
Then we can check the status of the docs and draw another conclusion from there: should we wait for them to be done (if it seems to take too long) or just dig into it ourselves?

**Comment by shahraizali** [comment]
Hey there guys, I saw your mention of the issue and I'm here to give my input on the issue at hand. I am managing the Python client library i.e. wrapping the backend API into a pip package and we faced the same issue of outdated docs. hence the issues are created to resolve it. For now, we will make the docs up to date since there is no active development on the backend rn we should be good for a small amount of time but I strongly believe that we should devise a structure to deliver updates about backend changes to all the teams that rely on the docs especially the SDK teams.

Regarding the updation of docs it will take a couple of days but there are not many changes especially for the GET requests the only major change so far is the implementation of pagination on the API but that is not mentioned in the docs so you can , like mentioned in a comment above, just ping the servers nodes for GET requests to get the latest object structure. however, for API calls that require signatures and stuff like POST/PATCH calls, etc, you won't be able to call most of those on the live nodes and would require local setup on your end. The local setup has not yet been made super easy and is a bit of hassle to set up but devs are working on dockerizing all of the nodes to work in one or just a couple of commands.

Nodes to ping for getting the latest API responses
BANK: 143.110.137.54
VALIDATOR: 54.183.17.224

NOTE: some endpoints have slight differences in the object types as well like in docs some objects keys have values as a string but API now returning an INT etc. so you have to be careful when comparing the API response to the docs and see what's changed. 
Example "default_transaction_fee" in [docs](https://thenewboston.com/bank-api/config) is a string but in [API Response](http://143.110.137.54/config) its an INT

**Comment by joshman1019** [comment]
@shahraizali Thanks!

**Comment by alfkonee** [comment]
> Hey there guys, I saw your mention of the issue and I'm here to give my input on the issue at hand. I am managing the Python client library i.e. wrapping the backend API into a pip package and we faced the same issue of outdated docs. hence the issues are created to resolve it. For now, we will make the docs up to date since there is no active development on the backend rn we should be good for a small amount of time but I strongly believe that we should devise a structure to deliver updates about backend changes to all the teams that rely on the docs especially the SDK teams.
> 
> Regarding the updation of docs it will take a couple of days but there are not many changes especially for the GET requests the only major change so far is the implementation of pagination on the API but that is not mentioned in the docs so you can , like mentioned in a comment above, just ping the servers nodes for GET requests to get the latest object structure. however, for API calls that require signatures and stuff like POST/PATCH calls, etc, you won't be able to call most of those on the live nodes and would require local setup on your end. The local setup has not yet been made super easy and is a bit of hassle to set up but devs are working on dockerizing all of the nodes to work in one or just a couple of commands.
> 
> Nodes to ping for getting the latest API responses
> BANK: 143.110.137.54
> VALIDATOR: 54.183.17.224
> 
> NOTE: some endpoints have slight differences in the object types as well like in docs some objects keys have values as a string but API now returning an INT etc. so you have to be careful when comparing the API response to the docs and see what's changed.
> Example "default_transaction_fee" in [docs](https://thenewboston.com/bank-api/config) is a string but in [API Response](http://143.110.137.54/config) its an INT

Hello Guys I was thinking we can suggest to the Core Teams to Generate an OpenAPI Document which can be used to standardize and communicate any changes easily for easier intergration

**Comment by joshman1019** [comment]
I did a small test using the "main" build of the SDK and I got data back! So that fun. Glad to see that it actually returns real data. 

![API Test Image](https://user-images.githubusercontent.com/36560776/100557790-3b2a6d80-3279-11eb-9b7d-56ba5baf6e4a.PNG)

**Comment by Mirch** [comment]
As I've opened #67, do you guys want to:
- keep integration tests on the API layer, or
- perform a sort of end-to-end tests for the whole system, that would actually test the system from the perspective of the users?

I personally believe the second option should definitely be part of our tests, so I don't really see the point of the first option anymore. What do you think?

**Comment by joshman1019** [comment]
Agreed on the second option.
