### ISSUE TITLE
Verify and change the models data types

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#53]
There are some issues regarding what data types we are currently using for some models, as compared to what the API is using. It would be nice to go through them and change them accordingly - we will see them when implementing integration tests, but it's a small task so it shouldn't take a lot of time.

E.g.: 
- port should be `int?`
- coins should be `BigDecimal`

**Comment by joshman1019** [comment]
I've been digging around in the API root today a bit. We may need to convert transaction amounts from string to int as well. I know I used string in the confirmation block transaction records and updated balance records because there was a bit of a conflict between some of the docs. But that can also be easily changed. I think the strings may have been a remnant of the older subdivided coins.

**Comment by nishp77** [comment]
I did some mistakes as well, will look into it

**Comment by mbilalakmal** [comment]
I have opened  a pull request for this but it is failing on account of the API still returning balance as string instead of int or decimal.

**Comment by Mirch** [comment]
> I have opened a pull request for this but it is failing on account of the API still returning balance as string instead of int or decimal.

Do you mean our class or the actual API?

**Comment by mbilalakmal** [comment]
Sorry I meant I changed the amount and balance type to `BigDecimal` but the tests are failing because `NewtonSoft.Json` is serializing them as String. And the tests are failing because there is no explicit JsonConverter given for String -> BigDecimal.

Example:

```
public class GetAccountBalanceAsync
        {
            [Fact]
            public async void AccountBalanceIsReturned()
            {
                var service = BuildValidatorServiceMock();

                var balance = await service.GetAccountBalanceAsync("9eca00a5-d925-454c-a8d6-ecbb26ec2f76");

                Assert.Equal(4294967051.0000000000000000, balance.Balance);
            }
        }
```

```
Message: 
    Newtonsoft.Json.JsonSerializationException : Error converting value "4294967051" to type 'System.Numerics.BigDecimal'. Path '[0].Balance', line 1, position 151.
    ---- System.InvalidCastException : Invalid cast from 'System.String' to 'System.Numerics.BigDecimal'.
  
```



On a different note: the Confirmation Validator API [docs](https://www.thenewboston.com/confirmation-validator-api/accounts) state that the response for `GET /accounts` will contain balance as a number while the response for `GET /accounts/<account_number>/balance` will contain balance as a string. Is this accurate or just a discrepancy in the docs?

**Comment by Mirch** [comment]
> Sorry I meant I changed the amount and balance type to `BigDecimal` but the tests are failing because `NewtonSoft.Json` is serializing them as String. And the tests are failing because there is no explicit JsonConverter given for String -> BigDecimal.
> 
> Example:
> 
> ```
> public class GetAccountBalanceAsync
>         {
>             [Fact]
>             public async void AccountBalanceIsReturned()
>             {
>                 var service = BuildValidatorServiceMock();
> 
>                 var balance = await service.GetAccountBalanceAsync("9eca00a5-d925-454c-a8d6-ecbb26ec2f76");
> 
>                 Assert.Equal(4294967051.0000000000000000, balance.Balance);
>             }
>         }
> ```
> 
> ```
> Message: 
>     Newtonsoft.Json.JsonSerializationException : Error converting value "4294967051" to type 'System.Numerics.BigDecimal'. Path '[0].Balance', line 1, position 151.
>     ---- System.InvalidCastException : Invalid cast from 'System.String' to 'System.Numerics.BigDecimal'.
>   
> ```
> 
> On a different note: the Confirmation Validator API [docs](https://www.thenewboston.com/confirmation-validator-api/accounts) state that the response for `GET /accounts` will contain balance as a number while the response for `GET /accounts/<account_number>/balance` will contain balance as a string. Is this accurate or just a discrepancy in the docs?

Let me check that and I'll be back

**Comment by xmac11** [comment]
> On a different note: the Confirmation Validator API [docs](https://www.thenewboston.com/confirmation-validator-api/accounts) state that the response for `GET /accounts` will contain balance as a number while the response for `GET /accounts/<account_number>/balance` will contain balance as a string. Is this accurate or just a discrepancy in the docs?

The docs are wrong. You can verify it with a [live server](http://157.230.75.222/accounts/9bfa37627e2dba0ae48165b219e76ceaba036b3db8e84108af73a1cce01fad35/balance).

**Comment by Mirch** [comment]
^ yup, just wanted to give an update on this. Looks like the number is the correct response.
