### ISSUE TITLE
Add .NET 5 Support 

### ISSUE THREAD

**Issue by alfkonee** [thenewboston-developers/dotnetcore-sdk#55]
I'd like to suggest we upgrade to use the DOTNET 5 SDK in Actions to gain support for C# 9 and .NET 5

**Comment by Mirch** [comment]
I don't think upgrading (and using the new features) would be the right thing to do. Mainly because .NET Core 3.1 has LTS, most cloud providers already have it available on their platforms (e.g. for function-as-a-service) and the next LTS version is going to be released in November 2021. 

Our main goal right now is to release the first version of a working product. Then we can look into supporting new versions of .NET. But I'm open to hearing other opinions :)

**Comment by joshman1019** [comment]
I would love to use the now supported "is not null" statement 😂. But yes, I agree. I'd say this would probably be more useful if we were building a front-end as well. There are a lot of new WebAPI client advantages, especially when it comes to setup. 

Oh and totally off topic, but here in the US it is Thanksgiving. I'm not sure where everyone is from, but Happy Thanksgiving to you all! It is definitely a day to celebrate what little good that we had this year even if you don't formally celebrate the holiday.

**Comment by Mirch** [comment]
There's definitely a lot of sweet new syntax stuff available 😄 but we'll see.

Well, Happy Thanksgiving to everyone celebrating it then!

**Comment by alfkonee** [comment]
We don't need to go all in to 5 yet. We could just add the SDK for the new language Features like the much more concise Pattern matching among many others.

Happy Thanksgiving to You guys as well

**Comment by Mirch** [comment]
> We don't need to go all in to 5 yet. We could just add the SDK for the new language Features like the much more concise Pattern matching among many others.
> 
> Happy Thanksgiving to You guys as well

But it would break compatibility with 3.1 anyway. We'll find a way to handle supporting multiple versions once we get the first release out.

I'll close this issue, as the suggestion has been noted and any action has been postponed :)
