### ISSUE TITLE
Plan the user-facing/interface/application layer

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/dotnetcore-sdk#67]
Call it whatever you want - these are the classes that the developers using our SDK will be working with. All the other classes (API wrappers, request/response models) will be marked as internal, and therefore invisible to the SDK users. 

A good starting point that I'm looking into right now is Stripe: https://stripe.com/docs/api/balance?lang=dotnet. I think it's a good idea to study the docs for a bit (if you haven't worked with it before) and get an idea on how they're handling the interactions.

I'll come up with some suggestions on structure and example usaged over the next days, but feel free to do the same :)

**Comment by joshman1019** [comment]
Yay! My favorite part!

**Comment by DylanGTech** [comment]
I think a core aspect of the upper-level interface should revolve around processing transactions for backend applications such as ASP.NET apps, so that once it successfully goes through, the depending processes can get the go-ahead.

Since there is really no way for the nodes to "reject" a valid transaction, there's a concern that the end user would send the wrong amount, and there would be no way to "refund" the transaction without incurring more fees from the validator and bank. I'd be curious to see what everyone's approach would be to that, if any (it is one of the downsides to crypto)

Because otherwise I'd think the simplest way to do it would be a -step process:
1.) Buyer submits request to application to purchase something with their provided account number. (transaction class)
2.) Application listens for an inbound transaction from the buyer's account. (listener thread with an optional timeout)
3.) Buyer sends coins to the app's account. Listener catches it. If it's the proper amount, return true or the completed transaction class. If not, return false or null.

Thoughts on this? It may not be general enough, as it talks about implementation more than interface.

**Comment by joshman1019** [comment]
It would be nice if the network included an "escrow" node. Something that simply received a request for payment, and received an intent to pay, and then compared the two. If they matched then the escrow would push the transaction to the bank. This could be an optional safety feature for retail use, but could be bypassed by people sending coins directly to other individuals. I suppose the escrow could sit outside of the network and would be a feature of a particular payment system. I'm not sure if forcing it to occur is appropriate though, because sometimes payments are made "automatically" or in bulk, kind of like our payments when we complete a task. It is just sent without us needing to manually request it. I do think this would be a good feature for a well-rounded payment processing system that would be used in the real world though. It would just require the particular processing system to implement this feature in their own way. 

Client to client communication is a no-go for me though without some sort of intermediary. This makes outgoing and incoming transactions more traceable, which would be a gigantic negative for any crypto network (and for wallet security in general).

**Comment by Mirch** [comment]
While this would be some nice functionality in some situations, I don't think it's our place to add it to the SDK - it's something that would be implemented by a payment system. Also, as @joshman1019 mentioned, you don't always want this behaviour for your transactions.

**Comment by Mirch** [comment]
I added a very small example on how I see this layer - you can take a look in #70. Let me know if you see any problems with this approach (perhaps with initialization of all services in this layer? naming?). If everything's good, we can create the tasks for this layer :)

**Comment by xmac11** [comment]
Should we consider adding support for pagination? Currently the client can only retrieve the first page and has to manually navigate to the next/previous page one by one, without the ability to jump to a specific page or modify the number of results. 
These options (`offset`, `limit`) were recently added to the [documentation](https://thenewboston.com/bank-api/accounts), so I think we should probably include them as well.

Also, is #30 still active?

**Comment by Mirch** [comment]
> Before starting user-facing classes, should we consider adding support for pagination? This will affect how these classes are designed. Currently the client can only retrieve the first page and has to manually navigate to the next/previous page one by one, without the ability to jump to a specific page or modify the number of results.
> These options (`offset`, `limit`) were recently added to the [documentation](https://thenewboston.com/bank-api/accounts), so I think we should probably include them as well.
> 
> Also, is #30 still active?

That's a good point. I'll create a task for that. 

Yes, it's still active, I just haven't had time to tackle it. It's up for grabs if you feel like it.

**Comment by Mirch** [comment]
Pagination is implemented. As I've already given a suggestion on how to implement it and it doesn't seem like anyone has a problem with it, I'll create the respective tasks :)
